### ISSUE TITLE
스케줄링 - 매주 목요일 마다 스터디 참여 여부

### ISSUE THREAD

**Issue by hoetaek** [Coding-Algorithm-for-the-Last-time/coalla-bot#2]
GitHub action schedule cron 사용하여 메시지 보내기
어떤 메시지든지 보낼 수 있는 함수 만들어 활용

**Comment by teacher-kiwi** [comment]
디스코드 코알라 채널에 참여여부 메시지 자동 발송

**Comment by hoetaek** [comment]
@teacher-kiwi 형 이건 내가 맡아서 진행해볼게
이슈 각자 알아서 가져가서 해결하면 될듯!

**Comment by hoetaek** [comment]
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
